import java.io.File
import java.util.Base64

plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

// CI-only: decode a base64 keystore secret so every CI debug APK is signed
// with the same key. Fresh runners otherwise auto-generate a new random
// debug key per run, so APKs from different runs don't share a signature.
// Locally KEYSTORE_BASE64 is unset and the default debug signing is unchanged.
val ciKeystore = System.getenv("KEYSTORE_BASE64")?.takeIf { it.isNotBlank() }?.let { b64 ->
    val file = File(rootDir, "build/ci-debug.keystore")
    file.parentFile?.mkdirs()
    file.writeBytes(Base64.getDecoder().decode(b64))
    file
}

android {
    namespace = "org.ravi.codeassist"
    compileSdk = 36

    signingConfigs {
        if (ciKeystore != null) {
            create("ciDebug") {
                storeFile = ciKeystore
                storePassword = System.getenv("KEYSTORE_PASSWORD")?.takeIf { it.isNotBlank() } ?: "android"
                keyAlias = System.getenv("KEY_ALIAS")?.takeIf { it.isNotBlank() } ?: "androiddebugkey"
                keyPassword = System.getenv("KEY_PASSWORD")?.takeIf { it.isNotBlank() } ?: "android"
            }
        }
    }

    defaultConfig {
        applicationId = "org.ravi.codeassist"
        minSdk = 23
        targetSdk = 34
        versionCode = 2
        versionName = "1.1"
    }

    buildTypes {
        debug {
            if (ciKeystore != null) {
                signingConfig = signingConfigs.getByName("ciDebug")
            }
        }
    }

    buildFeatures {
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }
}

dependencies {
    implementation(libs.jgit)
    implementation(libs.slf4j.nop)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.constraintlayout)
    implementation("com.google.android.material:material:1.14.0")
    
    // Coroutines and Lifecycle required for AgenticViewModel and StateFlows
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
}
